### ISSUE TITLE
Editable colors for charts?

### ISSUE THREAD

**Issue by frewinchristopher** [jolav/codetabs#1]
I haven't looked at the source code yet, but would it be difficult to make each chart color customizable?

This is something I could probably do in a pull request if there is interest.

**Comment by jolav** [comment]
I am pending to rewrite completely count loc and github star history backend into nodejs and some changes in frontend  in the nexts months.

I like your idea about chart color customizable and I will accept pull requests when that work is done

Thanks for your feedback

**Comment by frewinchristopher** [comment]
Excellent - I'll give it a shot!

**Comment by jolav** [comment]
Version 0.5.5 includes this
