### ISSUE TITLE
Suggestion: default the pie chart to non-blank lines (that is including comments), and provide a toggle

### ISSUE THREAD

**Issue by ell1e** [jolav/codetabs#10]
I suggest that the pie chart should default to showing to non-blank lines including comments, rather than as currently only the actual lines containing code. I think it's the most useful metric, since comments aren't easier to write than code, and a lack of comments also suggests less fleshed out code IMHO. It might be useful to also provide a toggle for those who prefer other metrics like the old one.

**Comment by jolav** [comment]
I like the idea. 
Since I have to replace [counting tool](https://github.com/cgag/loc) (is inactive) i willl implement it
