### ISSUE TITLE
Why do I get 429 for the first petition?

### ISSUE THREAD

**Issue by chiefeweight** [jolav/codetabs#11]
When I used Java to send petitions every 5500 ms, I only got 429. However, my code worked fine before Aug. Is anything new that I should know for using the API?
When I used the browser, everything is fine.
My Java code is basically using `org.apache.http.impl.client.CloseableHttpClient` and `org.apache.http.client.methods.HttpGet` to send the petition. The speed is controlled by `ScheduledExecutorService`.

**Comment by jolav** [comment]
> Is anything new that I should know for using the API?

No

Which endpoint returns 429 for the first petition. I will try to reproduce the error.

**Comment by chiefeweight** [comment]
The package I used is this: 
`<!-- HttpClient -->`
`<dependency>`
`<groupId>org.apache.httpcomponents</groupId>`
`<artifactId>httpclient</artifactId>`
`<version>4.5.10</version>`
`</dependency>`

And the code:

	public String httpGetString(String url) {
		String result = null;
		CloseableHttpClient http_client = HttpClients.createDefault();
		try {
			// set http method
			HttpGet http_method_get = new HttpGet(url);
			// customize response_handler
			ResponseHandler<String> response_handler = new ResponseHandler<String>() {
				@Override
				public String handleResponse(final HttpResponse response) {
					String response_body = null;
					HttpEntity entity = response.getEntity();
					if (entity != null) {
						try {
							response_body = EntityUtils.toString(entity);
						} catch (ParseException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						} catch (IOException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					}
					return response_body;
				}
			};
			// execution
			try {
				result = http_client.execute(http_method_get, response_handler);
			} catch (ClientProtocolException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			}
		} finally {
			try {
				http_client.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		return result;
	}

Then, when I call this method like this `System.out.println(httpGetString("https://api.codetabs.com/v1/loc?github=jolav/codetabs"));`, I get 429.

**Comment by jolav** [comment]
Its an nginx issue. My conf is
 
```
limit_req_zone  $limit_key  zone=three:10m   rate=12r/m;
limit_req zone=three;
```
I have modified 2nd line
```
limit_req zone=three burst=3;
```
Now doesnt return 429 for the first petition but this is valid for users who enter to browse some repositories and does it manually.
For users like you who use the api with a program at the moment the only thing I can think of is to make a first fake call.

I am really puzzled because this used to work and then suddenly a few months ago this bug appeared.
I think the bug appeared with the last server restart.
Server uptime 216 days

**Comment by jolav** [comment]
I restarted the server and now it seems that it is working correctly.
