### ISSUE TITLE
Count LOC: MATLAB identified as Objective-C

### ISSUE THREAD

**Issue by lrkrol** [jolav/codetabs#12]
I was testing the line count tool on my `lrkrol/SEREEGA` repository, which according to GitHub is 100% MATLAB. However, the tool recognised it as Objective-C. This obviously messed up the count of comment lines and thus the actual LoC count.

It would be good to support MATLAB. Commenting is explained [here](https://de.mathworks.com/help/matlab/matlab_prog/comments.html).

When multiple languages use the same file extension (`.m` in this case), perhaps a user choice can be provided for it to be interpreted as one or the other for the current repository.

**Comment by jolav** [comment]
Codetabs LOC is only an online wrapper around desktop count LOC programs. 

This type of issues depends on the counting program

Now i am using [cgag/loc](https://github.com/cgag/loc) but is inactive and i am looking for a replacement
