### ISSUE TITLE
count-loc-online: suggestion: checkbox to ignore "./vendor" which maybe should default to enabled?

### ISSUE THREAD

**Issue by ell1e** [jolav/codetabs#13]
I think a useful addition would be a checkbox to ignore `./vendor`, or a box to put ignore patterns, to this web UI: https://codetabs.com/count-loc/count-loc-online.html

Given `./vendor` is commonly used for third party code that is only put there to simplify building (and not actually developed on in-repo), I think it would also make sense to activate this exclusion by default but offer some obvious way to disable it in the web UI.

**Comment by jolav** [comment]
I like the idea

As soon as I've got a little time, I'll look into it.

**Comment by ell1e** [comment]
Okay, so I have a better idea:

I found out that GitHub supports overrides via a sort of `.gitignore`-alike syntax in the `.gitattributes` file in the repo root:

https://github.com/github/linguist#overrides

I think all files marked as `linguist-vendored` and `linguist-documentation` should be excluded by default, so codetabs would then not require any UI for it but just a pointer that this is configurable via `.gitattributes`/github linguist overrides.

**Comment by jolav** [comment]
Now LOC includes GitLab too and uses [https://github.com/boyter/scc](https://github.com/boyter/scc) tool for counting.

boyter/scc mostly supports .ignore files inside directories that it scans. Ignore files are 100% the same as .gitignore files with the same syntax, and as such scc will ignore files and directories listed in them. You can add .ignore files to ignore things like vendored dependency checked in files and such. The idea is allowing you to add a file or folder to git and have ignored in the count.  

This depends on the repos author and what he wants to write in ignore files.

I think best and simplest option will be include box to put ignore patterns,
