### ISSUE TITLE
Instructions on how to define `GITHUB_TOKEN`, `GITLAB_TOKEN`, and other constans

### ISSUE THREAD

**Issue by yin** [jolav/codetabs#16]
When running this code, I get a lot of error messages about undefined constants. I assume these need to be supplied somehow, but instruciton of how to acquire them and how to define them are missing the the `README.md`.

Can you provide a short explanation besides static the required dependencies?

When running the code I get the following:

```
mgagyi@third-gazometric:~/git/others../codetabs$ go run main.go
# github.com/jolav/codetabs/weather
weather/weather.go:108:23: undefined: WEATHERUNLOCKED_APPID
weather/weather.go:109:24: undefined: WEATHERUNLOCKED_KEY
weather/weather.go:114:22: undefined: OPENWEATHER_KEY
weather/weather.go:117:20: undefined: WEATHERAPI_KEY
# github.com/jolav/codetabs/loc
loc/github.go:38:43: undefined: _utils.GITHUB_TOKEN
loc/gitlab.go:42:34: undefined: _utils.GITLAB_TOKEN
# github.com/jolav/codetabs/stars
stars/github.go:108:43: undefined: _utils.GITHUB_TOKEN
stars/github.go:149:45: undefined: _utils.GITHUB_TOKEN
stars/github.go:243:44: undefined: _utils.GITHUB_TOKEN
stars/gitlab.go:88:36: undefined: _utils.GITLAB_TOKEN
stars/gitlab.go:160:34: undefined: _utils.GITLAB_TOKEN
```

**Comment by jolav** [comment]
That constants are personal keys to access different services

Github Tokens
https://github.com/settings/tokens

Gitlab tokens
https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html
Create a personal access token 

Weather Apis
http://www.weatherunlocked.com/products/weather-api/overview
https://openweathermap.org/current
https://www.weatherapi.com/docs/
