### ISSUE TITLE
Repository search

### ISSUE THREAD

**Issue by ghost** [jolav/codetabs#18]
This is actually unrelated to codetabs, but is an idea I've had and I wanted to write it somewhere.
It would be nice to have a search website for github, gitlab, etc that let's you find repositories to practice with, based on number of lines and some quality of code metric. Because from following a tutorial to contributing to a big project there is quite a leap, and I think working on small projects that are already done to check your progress would be a nice middle ground. Right now I can find projects like this in [Project Based Learning](https://github.com/practical-tutorials/project-based-learning#project-based-learning), but it would be better to be able to filter projects by language, below 1k words for example and get a list of projects with a brief description and sorted by stars or code quality. The closest thing that I know off is [Awesome Open Source](https://awesomeopensource.com/).

**Comment by jolav** [comment]
Although it is a great idea, at this time it is out of the scope of the project.
