### ISSUE TITLE
Finding LoC for IntelliJ returns 504

### ISSUE THREAD

**Issue by SUPERCILEX** [jolav/codetabs#2]
https://api.codetabs.com/count-loc/get?repo=JetBrains/IntelliJ-Community

Bigger repos like Linux work just fine so I'm not sure what's going on.

**Comment by jolav** [comment]
[torvalds/linux](https://github.com/torvalds/linux) weights 191mb, [JetBrains/IntelliJ-Community](https://github.com/JetBrains/IntelliJ-Community) weights 398 mb and request returns 504 before response is sent.

I had not foreseen such large files. I must dig a little more before taking a solution

**Comment by SUPERCILEX** [comment]
Oh wow, that's huge! I'm guessing it's those dozens of thousands of tags they use 😂.

I'd understand if you want to set the line there and consider the repo to be too big (though I would still love to get stats on it! 😁).

**Comment by jolav** [comment]
> though I would still love to get stats on it! 😁

https://gist.github.com/jolav/83cf364719c472f9d9a1ea1aa7fa9b99

**Comment by jolav** [comment]
I use nginx as a reverse proxy in front of applications.
I have modified nginx configuration about timeouts and it looks like its working at least until a much larger repository appears

**Comment by SUPERCILEX** [comment]
👍. Good enough for me!
