### ISSUE TITLE
Code ignored for PQCraft/CaveCube

### ISSUE THREAD

**Issue by PQCraft** [jolav/codetabs#21]
Typing in my project [CaveCube](https://github.com/PQCraft/CaveCube) (`PQCraft/CaveCube`) shows this ignoring all the C files:
![Screenshot_20220628_003310](https://user-images.githubusercontent.com/58464017/176093513-5aa7cc01-f458-447c-8267-4e499cf44f73.png)

**Comment by jolav** [comment]
Codetabs/loc is only an online wrapper for github.com/boyter/scc.

In https://github.com/boyter/scc#ignore-files we can read about .gitignore files.

So if i download your repo in my computer and delete .gitignore it works

Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
C Header                    91     22119     2389      6540    13190        512
C                           21     21245     2353      2195    16697       3813
Makefile                     2       180       39         0      141          2
License                      1        21        4         0       17          0
Plain Text                   1        20        9         0       11          0
───────────────────────────────────────────────────────────────────────────────
Total                      116     43585     4794      8735    30056       4327`
`

**Comment by PQCraft** [comment]
@jolav I don't believe the .gitignore is the problem as it doesn't ignore the code folder. It ignores all and then exempts the files needed which include some files in the main directory and some folders include the code folder (`src`).

**Comment by PQCraft** [comment]
Ah ok thanks :+1:
