### ISSUE TITLE
Doesn't work on sites with relative imports

### ISSUE THREAD

**Issue by ajmeese7** [jolav/codetabs#22]
For an example, try visiting `https://api.codetabs.com/v1/proxy/?quest=https://github.dev/`.

If you open the console, you can see that requests are being made to endpoints like `https://api.codetabs.com/static/splash-screen-styles.css`, which are obviously failing because they don't exist. The proxy should download all dependencies with the proper URL root and *then* return the data, instead of pulling the root back and downloading dependencies afterwards.

Not trying to be a jerk, just noticed this issue and wanted to point it out. Cheers!

**Comment by jolav** [comment]
The original idea was to make a CORS proxy to be able to collect individual assets such as photos, json, xml , etc.

This is not intented to be a complete browse proxy. Many times I have been tempted to move in that direction, but that's a whole different beast

Thanks a lot for your feedback
