### ISSUE TITLE
Proxy gives access internal server(s)

### ISSUE THREAD

**Issue by grumpinout1** [jolav/codetabs#24]
Hi, 

I was checking out a project that makes use of the CORS proxy, and noticed that I was able to access the internal server, which should not be possible. 

The following URL shows the default Nginx page of your server: https://api.codetabs.com/v1/proxy?quest=http://localhost. This introduces a security risk if a hacker brute forces directories to find hidden endpoints. 

Happy new year and kind regards

Grumpinout

**Comment by grumpinout1** [comment]
Implementing https://github.com/doyensec/safeurl should protect you against any attacks

**Comment by jolav** [comment]
Thanks a lot for the feed

**Comment by jolav** [comment]
[v0.7.20](https://github.com/jolav/codetabs/commit/e5b6da438da8f0a35aa0ba8854177886f562c392) fixes this
