### ISSUE TITLE
PROXY Service temporarily suspended (service now operating normally)

### ISSUE THREAD

**Issue by jolav** [jolav/codetabs#27]
I have removed PROXY service.

Looks like someone is using it for phishing.

**Comment by shinigami1908** [comment]
Any idea when will this be up ?

**Comment by jolav** [comment]
I think I will have a new version today

Then ask cloudflare to unblock the path.

At that point the proxy can no longer be able to use be used for normal browsing.
The original idea was to make a CORS proxy to be able to collect individual assets like photos, json, xml , etc. 
It was not intended to be a full proxy for browsing.

**Comment by marcelozarate** [comment]
Who used this for browsing? The abusers ruined it for me that only needed a small JSON in a script and bypassing CORS.

**Comment by jerryfromearth** [comment]
Hello @jolav , the "new version" seems to not function the same way as the old version.

At **https** https://eleven-germany.de/test/ , we are using your fantastic CORS proxy to load the **http** resource `http://elevenlogcollector-env.js6z6tixhb.us-west-2.elasticbeanstalk.com/ElevenServerLiteSnapshot` . Right now, we still get the error:
`Access to fetch at 'https://api.codetabs.com/v1/proxy/?quest=http://elevenlogcollector-env.js6z6tixhb.us-west-2.elasticbeanstalk.com/ElevenServerLiteSnapshot' from origin 'https://eleven-germany.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
So....the "CORS proxy" part doesn't seem to work?

Much appreciated if you could point me to the right direction :)

**Comment by jolav** [comment]
Cloudflare is still blocking the path https://api.codetabs.com/v1/proxy/

**Comment by jolav** [comment]
While we wait for Cloudflare you can use

https://api.codetabs.com/v1/tmp/?quest=
instead of
https://api.codetabs.com/v1/proxy/?quest=

**Comment by jolav** [comment]
Service working 
You can use again normal path 
```
https://api.codetabs.com/v1/proxy/?quest=
```
"tmp" path will be active for a period of time so that everyone has time to change it.
