### ISSUE TITLE
bug: cannot recognize GNUmakefile as Makefile Language

### ISSUE THREAD

**Issue by shynur** [jolav/codetabs#29]
To save your time, please use my test example directly:

- Repo: <https://github.com/shynur/tmp>
- Line Count: <https://api.codetabs.com/v1/loc/?github=shynur/tmp&branch=main>

**Comment by jolav** [comment]
codetabs/loc is only an online wrapper for github.com/boyter/scc. SCC supports makefile

I know nothing about makefile or GNUmakefile. But maybe you need to indicate the file extension

**Comment by shynur** [comment]
> jolav: maybe you need to indicate the file extension

They don't need extension.  It is a convention that `"GNUmakefile"`/`"Makefile`" uses *Makefile* language.

Here, `"Makefile"` is recognized by codetabs/loc correctly, but `"GNUmakefile"` not.  That is the problem.

> jolav: github.com/boyter/scc

Thanks.  I shall take a look.

**Comment by jolav** [comment]
Here is the list of languages supported

**Comment by shynur** [comment]
> jolav: <https://github.com/boyter/scc/blob/master/LANGUAGES.md>

Thanks.  I've reported as [boyter/scc/issues/395](https://github.com/boyter/scc/issues/395), and thus issue can be closed now.
