### ISSUE TITLE
show a total number of LOC not just by language type

### ISSUE THREAD

**Issue by shoulders** [jolav/codetabs#3]
When people say how many lines of code their project has they generally mean across all of the languages used.

This would be a nice addition below the pie chart.

Thanks

**Comment by jolav** [comment]
You're right.
It is done
Thanks for the feedback

**Comment by shoulders** [comment]
shall i close this issue or will you close it with a commit?

P.S. your 'Count LOC online' is very easy to use and the simple metrics allow for describing a program's complexitiy or by giving an indication on how big it is gettings over time. The GitHub integration is a brilliant feature.

**Comment by jolav** [comment]
Thanks
