### ISSUE TITLE
api.codetabs.com/v1/loc always returns error

### ISSUE THREAD

**Issue by joelbarmettlerUZH** [jolav/codetabs#5]
Your API-Endpoint under "https://api.codetabs.com/v1/loc?github=jolav/betazone" either returns the Error message ``` {"Error": "Valid format is 'api.codetabs.com/v1/{service}?{param}=value' .Please read our docs at https://codetabs.com"}``` or the Error ```{ "Error": "jolav/betazone doesn't exist" }```, or even ```{ "Error": "Cant create temporal dir for jolav/betazone"}```, but never the actual values. Which error is being displayed seems to have no pattern. 
Until yesterday, 10th of February, everything worked fine. 
The same behavior occurs on different devices, different OS and different networks (tested via VPN).

**Comment by RouNNdeL** [comment]
The whole site is dead. When attempting User/Repo based count it always returns a "User/Repo doesn't exist error". When uploading a file, a "Error creating folder temp/loc/XXXX" error appears.

**Comment by jolav** [comment]
Sorry, a restart fixed the error.
I'm going crazy trying to find how to solve this error that appears every few days
`2019/02/23 07:47:13 ERROR opening hits file open ./logs/hits.log: too many open files`
`2019/02/23 07:47:13 http: Accept error: accept tcp 127.0.0.1:3510: accept4: too many open files; retrying in 80ms`
At the moment the only solution is to make a restart
