### ISSUE TITLE
why i got this ?

### ISSUE THREAD

**Issue by minanagehsalalma** [jolav/codetabs#6]
![image](https://user-images.githubusercontent.com/20546638/59563233-5aa6e980-9037-11e9-8efe-082dc44a4700.png)

**Comment by jolav** [comment]
If i visit "http://moooooon.epizy.com/jsoginandextract.html" i get on console
`TypeError: str.match(...) is null on line 25`
because script fails on jsoginandextract.html:25:31

So cors-proxy cant proxy a resource that is not working

**Comment by minanagehsalalma** [comment]
> If i visit "http://moooooon.epizy.com/jsoginandextract.html" i get on console
> `TypeError: str.match(...) is null on line 25`
> because script fails on jsoginandextract.html:25:31
> 
> So cors-proxy cant proxy a resource that is not working

it is working ... but does it make any sense that the resource  is local Accessibility only ?

**Comment by minanagehsalalma** [comment]
@jolav

**Comment by jolav** [comment]
> it is working ... but does it make any sense that the resource is local Accessibility only ?

I don't understand what you mean by that. What resource do you mean? 

You mean this code in http://moooooon.epizy.com/jsoginandextract.html ?
```
const url = 'http://192.168.1.1/';
http.open('get', url, false);
```

**Comment by minanagehsalalma** [comment]
> > it is working ... but does it make any sense that the resource is local Accessibility only ?
> 
> I don't understand what you mean by that. What resource do you mean?
> 
> You mean this code in http://moooooon.epizy.com/jsoginandextract.html ?
> 
> ```
> const url = 'http://192.168.1.1/';
> http.open('get', url, false);
> ```

@jolav  yes

**Comment by jolav** [comment]
> but does it make any sense that the resource is local Accessibility only ?

That's a question for the owner of the site.

**Comment by minanagehsalalma** [comment]
> > but does it make any sense that the resource is local Accessibility only ?
> 
> That's a question for the owner of the site.

@jolav  you mean the server can't access a client devices only like ( local devices )

**Comment by minanagehsalalma** [comment]
it seems i miss understood your site

**Comment by jolav** [comment]
Ok, closing issue
