### ISSUE TITLE
Color of squares differs from pie's

### ISSUE THREAD

**Issue by Piruzzolo** [jolav/codetabs#7]
In the language percentage pie graph, when clicking/tapping on a slice of the pie, the color changes. The square on it with the language name label also changes (accordingly, it should), but is instead always late, i.e. when re-clicking on the pie, it gets the color the slice had one click before

**Comment by jolav** [comment]
You're right.

As soon as I've got a little time, I'll look into it.

**Comment by jolav** [comment]
Issue is related to these chartjs issues

[Dynamically update tooltip when hovering](https://github.com/chartjs/Chart.js/issues/5204)  
[Update tooltip content and styling on update()](https://github.com/chartjs/Chart.js/pull/6181)  

At the moment the solution is not to show tooltip colors.

```js
toolips: {
  displayColors: false,
}
```
