### ISSUE TITLE
Ability to pass repository from url to count lines of code

### ISSUE THREAD

**Issue by khoren93** [jolav/codetabs#9]
It would be nice if we could pass the repository via url, something like this
https://codetabs.com/count-loc/count-loc-online.html/#khoren93/swifthub

and also I would like to know if the license allows integrating the module 'count lines of code' into [my project](https://github.com/khoren93/SwiftHub)?

Thanks!

**Comment by jolav** [comment]
> It would be nice if we could pass the repository via url, something like this
> https://codetabs.com/count-loc/count-loc-online.html/#khoren93/swifthub

You can
GET Request -> https://api.codetabs.com/v1/loc?github=username/reponame
example :
[https://api.codetabs.com/v1/loc?github=jolav/betazone ](https://api.codetabs.com/v1/loc?github=jolav/betazone )

> and also I would like to know if the license allows integrating the module 'count lines of code' into [my project](https://github.com/khoren93/SwiftHub)?

Sure

**Comment by khoren93** [comment]
Thanks
